# Generated by Django 3.2.13 on 2022-05-12 15:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson_5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='fresh_period',
            field=models.DurationField(default=datetime.timedelta(5), help_text='Use this field when you need info about bouquet time duration', null=True),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='price',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='discount',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='invoice_doc',
            field=models.FileField(max_length=1000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='second_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='could_use_in_bouquet',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='delivered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='wiki_page',
            field=models.URLField(default='https://ru.wikipedia.org/', null=True, unique_for_date='delivered_at'),
        ),
    ]
