# Generated by Django 3.2.13 on 2022-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0002_auto_20220512_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='invoice_doc',
            field=models.FileField(max_length=1000, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
