# Generated by Django 3.2.13 on 2022-05-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0003_alter_client_invoice_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='invoice_doc',
            field=models.FileField(max_length=1000, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
