# Generated by Django 3.2.13 on 2022-05-12 17:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_5', '0004_alter_client_invoice_doc'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bouquet',
            managers=[
                ('shop', django.db.models.manager.Manager()),
            ],
        ),
    ]
